name: autobuild-luci-app-webadmin

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
      - "r*"

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          #- i386_pentium-mmx
          #- loongarch64_generic
          #- mips_mips32
          #- mipsel_24kc
          #- mipsel_mips32
          - x86_64

    permissions:
      actions: write
      contents: write
      
    steps:
      - name: Fetch latest release tag
        run: |
          #通过url获取
          latest_tag=$(curl -s https://github.com/uiouio001/luci/releases/latest | jq -r '.tag_name')

          if [ "$latest_tag" = "null" ] || [ -z "$latest_tag" ]; then
            #直接设置为当天日期
            latest_tag="r$(date +"%Y%m%d")"
          fi
          
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          echo "✅ Found release tag: ${{ env.LATEST_TAG }}"
          
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
    
      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-openwrt-24.10
          FEEDNAME: packages_ci
          PACKAGES: luci-app-webadmin
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Organize files
        run: |
          # 创建存放目录
          mkdir -p webadmin_${{ matrix.arch }}
          
          ls bin/packages
          
          cp -f bin/packages/${{ matrix.arch }}/packages_ci/*.ipk webadmin_${{ matrix.arch }}/
          
          ls webadmin_${{ matrix.arch }}
          
      - name: Create install.sh scripts
        run: |
          cat <<EOF > webadmin_${{ matrix.arch }}/install.sh
          #!/bin/sh
          opkg update
          if [ $? -ne 0 ]; then
              echo "update failed。"
              exit 1
          fi
          opkg install webadmin_${{ matrix.arch }}/*.ipk
          EOF
          
          chmod +x webadmin_${{ matrix.arch }}/install.sh

      - name: Move app directories to makeself
        run: |
          mv webadmin_${{ matrix.arch }} makeself/

      - name: Fetch latest release tag
        run: |
          #通过url获取
          latest_tag=$(curl -s https://github.com/uiouio001/luci/releases/latest | jq -r '.tag_name')

          if [ "$latest_tag" = "null" ] || [ -z "$latest_tag" ]; then
            #直接设置为当天日期
            latest_tag="r$(date +"%Y%m%d")"
          fi
          
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          echo "✅ Found release tag: ${{ env.LATEST_TAG }}"
          
      - name: Create self-extracting packages
        run: |
          cd makeself
          ./makeself.sh webadmin_${{ matrix.arch }}/ webadmin_${{ matrix.arch }}_${{ env.LATEST_TAG }}.run "by github action" ./install.sh

      - name: Check file sizes
        run: |
          ls -lh makeself/webadmin_*.run

      - name: Upload packages
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ env.LATEST_TAG }}
          release_name: Release ${{ env.LATEST_TAG }}
          files: |
            bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
            makeself/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
