name: build-luci-app-turboacc-mtk

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    env:
      PACKAGES: luci-app-turboacc-mtk
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          #- i386_pentium-mmx
          #- loongarch64_generic
          #- mips_mips32
          #- mipsel_24kc
          #- mipsel_mips32
          - x86_64

    permissions:
      actions: write
      contents: write
    
    steps:
      - name: Init GITHUB_ENV
        run: |
          tag_name="r$(date +"%Y%m%d")"
          echo "TAG_NAME=$tag_name" >> "$GITHUB_ENV"

          release_name="Release r$(date +"%Y%m%d")"
          echo "RELEASE_NAME=$release_name" >> "$GITHUB_ENV"
          
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-openwrt-24.10
          FEEDNAME: packages_ci
          PACKAGES: ${{ env.PACKAGES }}
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Organize files
        run: |
          # 创建存放目录
          mkdir -p app_${{ matrix.arch }}
          
          cp -f bin/packages/${{ matrix.arch }}/packages_ci/*.ipk app_${{ matrix.arch }}/
          
          ls app_${{ matrix.arch }}
          
      - name: Create install.sh scripts
        run: |
          cat <<EOF > app_${{ matrix.arch }}/install.sh
          #!/bin/sh
          opkg update
          if [ $? -ne 0 ]; then
              echo "update failed。"
              exit 1
          fi
          opkg install app_${{ matrix.arch }}/*.ipk
          EOF
          
          chmod +x app_${{ matrix.arch }}/install.sh

      - name: Move app directories to makeself
        run: |
          mv app_${{ matrix.arch }} makeself/

      - name: Create self-extracting packages
        run: |
          cd makeself
          ./makeself.sh app_${{ matrix.arch }}/ ${{ env.PACKAGES }}_${{ matrix.arch }}_${{ env.TAG_NAME }}.run "by github action" ./install.sh

      - name: Check file sizes
        run: |
          ls -lh makeself/*.run

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "bin/packages/${{ matrix.arch }}/packages_ci/*.ipk,makeself/*.run"

